mysql-database-url: jdbc:mysql://47.112.143.221:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
mysql-user-name: root
mysql-user-password: a784860246

